name: .NET Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'


    - name: Publish Native AOT
      run: dotnet publish -c Release -r win-x64

    - name: Create Release Archive
      run: Compress-Archive -Path bin/Release/net8.0/win-x64/publish/* -DestinationPath play-win-x64.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: play-win-x64
        path: play-win-x64.zip